# Header
menu:                      # Links in the navigation bar
  Home: /
  Archives: /archives
  About: /about
# rss: /atom.xml #暂时没搞明白，先不配置（

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true                   # Display banner
  url: pics/banner.jpg           # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: flas               # Display banner on all pages instead of only the home page

# Appearance
hue: 180                         # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color

# Personal info
avatar: pics/avatar.jpg          # Path to the avatar image relative to /source
# author: Your Name
# subtitle: This is the subtitle
links:
  - name: Twitter
    icon: fa-brands fa-twitter      # Find icon codes at https://fontawesome.com/search
    url: https://twitter.com
  - name: Steam
    icon: fa-brands fa-steam
    url: https://store.steampowered.com
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - recent_posts
#      - archive

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 3             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: true
    enableQQ: true
    appId: dCKwhYXrHlbvPLeJ7kjuo0Sw-gzGzoHsz
    appKey: aUgZBlUsXWheyTITsfhznbhz
    placeholder: 留个脚印嘛 owo
    avatar: retro # Gravatar 头像展示方式。不能使用不知道为啥
    pageSize: 10 # 评论列表分页，每页条数。
    highlight: true
    meta: [nick, mail, link] # 评论者相关属性。[nick, mail, link]
    visitor: true # 是否记录访问次数
    serverURLs: # api地址
    requiredFields: [mail] # 设置必填项 [nick,mail,link]
    # 以下需要 //cdn.jsdelivr.net/gh/HCLonely/Valine@latest/dist/Valine.min.js
    tagMeta: ["博主","小伙伴","有缘人"] # 标签要显示的文字["博主","小伙伴","访客"]
    master: ["dbac733e8273f05ffbb7d518c0a00861"] # md5 加密后的博主邮箱 逗号隔开
    friends: ["29965666e23ccf00db9b367d822aafd7"] # md5 加密后的小伙伴邮箱 逗号隔开
    metaPlaceholder: {"nick":"QQ号／昵称","mail":"邮箱(可显示Gravatar头像)","link":"个人网站(选填)"} # meta placeholder 内容
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID:
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
